<a href="https://colab.research.google.com/github/Meemansha-spec/Complete-Python-3-Bootcamp/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We are going to implement the fundamentals of tensorflow

## Introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
## check the num of dimensions
scalar.ndim

0

In [4]:
## create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of vecyor
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
## create aother matrix
matrix2 = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype = tf.float16)

In [9]:
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
matrix2.ndim

2

In [11]:
## lets create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6,]],
                      [[7,8,9],
                       
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])

In [12]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
tensor2 = tf.constant([[[1,2,3],
                        [4,5,6],
                        [6,7,8]]])

In [15]:
tensor2.ndim

3

## What we created so for
* scalar -no dimension
* vector -1D
* matrix - 2D
* tensor - ndimensional

### creating tensors with variables

In [16]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
## lets try change one of the elements in changeable tensor
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
## you cannot change a `constant tensor`
#unchangeable_tensor[0].assign(7)

## Creating Random tensor

In [19]:
## create random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
random2 =  tf.random.uniform(shape = (3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.32163382, 0.84037006],
       [0.5074445 , 0.15991473],
       [0.89519393, 0.9658903 ]], dtype=float32)>

##shuffle the order of the elements in tensors

In [21]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

In [22]:
tf.random.set_seed(42)
shuffled  = tf.random.shuffle(not_shuffled,seed = 42)
shuffled  ## if you keep running it again and again theorder changes irrespective of the seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

In [23]:
tf.ones([10,7]) ## create a tensor of all ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
## create a tensor of all zeroes
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors (tensors run on GPU much faster)

In [25]:
## you can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A,shape = (2,12))
B = tf.constant(numpy_A)

In [27]:
A

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [28]:
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

## Getting information from tensors
* When dealing with tensors you should know about this information

*   Shape
*   Rank
*   Axis or dimension
*   Size








In [29]:
## createa rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape =(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [31]:
2*3*4*5

120

In [32]:
## Get various attributes of our tensor
print("Datatype of every element:" , rank_4_tensor.dtype)
print("Name of dimesnions(rank):" , rank_4_tensor.ndim)
print("shape of tensor" , rank_4_tensor.shape)
print("elements along the 0 axis",rank_4_tensor.shape[0])
print("elements along the last axis",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:" , tf.size(rank_4_tensor))
print("Total number of elements in our tensor:" , tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Name of dimesnions(rank): 4
shape of tensor (2, 3, 4, 5)
elements along the 0 axis 2
elements along the last axis 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


## Indexing in tensors
* can be indexed just like python list

In [33]:
## Get the first two elements
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [34]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
## Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [38]:
## create a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
rank_2_tensor[:1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [40]:
rank_2_tensor[-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [41]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [42]:
## add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
## alternative
tf.expand_dims(rank_2_tensor , axis = -1)  ##-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [44]:
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulation tensors
* BASIC OPERATIONS

In [45]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
## original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [48]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [49]:
## we can use the tensorflow built in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [51]:
tensor % 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 7],
       [3, 4]], dtype=int32)>

## Matrix multiplication
**In machine learning , matrix multiplications is one of the most common tensors operations**

In [52]:
## Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor , tensor) ## dot product

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [53]:
tensor * tensor ## element wise

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [54]:
tensor @ tensor ## dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [55]:
tensor.shape

TensorShape([2, 2])

In [56]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
Z = tf.constant([[12,13,14],
                 [15,16,17]])

In [57]:
X.ndim

2

In [58]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [59]:
Z

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 13, 14],
       [15, 16, 17]], dtype=int32)>

In [60]:
X @ Z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 42,  45,  48],
       [ 96, 103, 110],
       [150, 161, 172]], dtype=int32)>

In [61]:
X * Y ## Element wise is possible

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [62]:
X @ Y ## dot-product not possible

InvalidArgumentError: ignored

In [ ]:
# change the shape of `Y`
ynew = tf.reshape(Y,shape = (2,3))


In [ ]:
Y

In [ ]:
tf.matmul(X,ynew)

**Dot product**
Matrix multiplication is also refered to as the dot product
You can perform it using:

*   `tf.matmul()`
*   `tf.tensordot()`



In [ ]:
tf.tensordot(tf.transpose(X) ,Y,axes = 1)

In [ ]:
X

In [ ]:
Y

In [ ]:
tf.matmul(X,tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

In [ ]:
## check the value of Y and transposed Y
print("Normal Y:")
print(Y , "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

**mostly when axes doesnot line up , use transpose rather than reshape**

## Changing the datatype of tensors

In [ ]:
## create a new tensor with default datatype
B = tf.constant([1.7,7.4])
B.dtype

In [ ]:
C = tf.constant([7,10])
C

In [ ]:
## REDUCED PRECISION
D = tf.cast(B,dtype = tf.float16)
D, D.dtype

## Aggregating Tensors

In [ ]:
D = tf.constant([-7,-10])
D

In [ ]:
tf.abs(D)

## Lets go through the following forms of aggregation

*   Get the minimum
*   Get the maximum
*   Get the mean of a tensor
*   Get the sum of a tensor





In [ ]:
## Minimum
Min = tf.constant([[2,3],[4,5]])
tf.reduce_min(Min) ## prints out the minimum number

In [ ]:
Min

In [ ]:
x = tf.constant([[2.,3.,4.],
                 [5.,6.,8.]])
y = tf.constant([[5.,6.,7.],
                 [8.,9.,10]])

In [ ]:
x.shape

In [ ]:
y.shape

In [ ]:
y.ndim

In [ ]:
tf.math.minimum(x,y)

In [ ]:
## Max
Max = tf.constant([[2,3],[4,5]])
tf.reduce_max(Max)

In [ ]:
## argmax
tf.math.argmax(x)

In [ ]:
x

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])

tf.math.argmax(B,0) ## GOES COLUMN WISE

In [ ]:
B

In [ ]:
## MEAN of tensor
tf.reduce_mean(B) ## Calculates the mean

In [ ]:
## sum of tensor
tf.reduce_sum(B)

## find the standard deviation and variance of tensor

In [ ]:
E = tf.constant(np.random.randint(1,100,size = 50))
E

In [ ]:
E.dtype

In [ ]:
E1 = tf.cast(E,dtype = tf.float32)

In [ ]:
tf.math.reduce_std(E1) ## STANDARD DEVIATION

In [ ]:
tf.math.reduce_variance(E1) ## VARIANCE

## Squeezing the tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]) , shape = (1,1,1,50))

In [ ]:
G

In [ ]:
G.ndim

In [ ]:
G.shape

In [ ]:
tf.size(G)

In [ ]:
G_squeezed = tf.squeeze(G)  ## removes dimension of size 1

In [ ]:
G_squeezed

## One hot encoding

In [ ]:
## create a list of indices
some_list = [0,1,2,3]

tf.one_hot(some_list,depth=4)

In [ ]:
tf.one_hot(some_list , depth = 4 , on_value = 'I am Lord Voldemort' , off_value = 'Hogwarts is my home')

### square , log , square root

In [ ]:
H = tf.range(1,10)

In [ ]:
tf.square(H)

In [ ]:
H = tf.cast(H , dtype = tf.float32)

In [ ]:
tf.math.sqrt(H)

In [ ]:
tf.math.log(H)

## Exploring tensorflow and numpy compatibility

In [ ]:
J = tf.constant(np.array([3,7,10]))
J

In [ ]:
np.array(J) , type(np.array(J))

In [ ]:
## convert tensor J to Numpy array
J.numpy()

In [ ]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype , tensor_J.dtype

## Finding access to GPUs

In [63]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [65]:
!nvidia-smi

Wed May 12 08:10:59 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    31W / 250W |    351MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------